### ISSUE TITLE
recent.lua after source removal

### ISSUE THREAD

**Issue by ratnamhof** [hacel/mpv-scripts#1]
Dear developer(s),

Thank you very much for the `recent.lua` script! Very nice functionality! Thank you so much for making and sharing it!

I encountered a link to this plugin on the mpv user scripts github page and thought it was very useful functionality. Two circumstances that I encountered or can think of:

1. The source file has been deleted/moved/renamed after the creation of the history.log file
2. The source file has been deleted/moved/renamed after displaying the history.log onto the mpv OSD

For my setup this leads to a hard abort of the mpv player (crash?). To me it seems more desirable to in the mpv OSD omit those files from the history log that are no longer available (point 1) and to throw a message/warning onto the OSD when a file is selected that is no longer available (point 2). To achieve this behaviour in my copy of `recent.lua` I have added the following function (copied from [stackoverflow](https://stackoverflow.com/questions/4990990/check-if-a-file-exists-with-lua)):
```
function file_exists(name)
    local f=io.open(name,"r")
    if f~=nil then io.close(f) return true else return false end
end
```
and in the function `read_log_table` substituted `return {title = t, path = p}` with:
```
if file_exists(p) then return {title = t, path = p} else return nil end
```
and in the function `load` substituted `mp.commandv("loadfile", list[#list-start-choice].path, "replace")` with:
```
if file_exists(list[#list-start-choice].path) then mp.commandv("loadfile", list[#list-start-choice].path, "replace") else mp.osd_message("Failed loading file: "..list[#list-start-choice].title) end
```

My apologies for posting this comment here as technically it does not concern a script issue, but I just wanted to share this as perhaps you (the developer) or someone else may like this behaviour as well and like to incorporate it in their `recent.lua` script. If not, please feel free to ignore my comments ;)

Thanks again for sharing your great work!!

With kind regards,
Happy user

**Comment by hacel** [comment]
I did notice this behavior occasionally but I didn't think it was worth addressing. Since you pointed it out and basically did the work, I see no reason not to update the script with your suggestions. Thank you.

**Comment by hacel** [comment]
Didn't like the idea of omitting the entries from the OSD as there are cases where I would like to know what exactly is in the history even if the file no longer exists. I think the ability to delete the files with `DEL` is sufficient.

**Comment by hacel** [comment]
I reverted the change as I was told the crashes shouldn't be happening in the first place. I opened an issue in mpv.
