### ISSUE TITLE
Streamings and Youtube videos won´t load

### ISSUE THREAD

**Issue by RBNXI** [hacel/mpv-scripts#2]
When a Youtube video or a magnet link or some streaming link is in the history, when loaded it gives an error "failed loading file". It works fine with local files and .torrent files (with webtorrent script).

**Comment by hacel** [comment]
You're right I hadn't considered how URLs would work in my last commit, will fix soon.

**Comment by hacel** [comment]
I reverted the change so they should work now. But you could you please give me an example of what these links look like? Because I don't think they should've worked in the first place.

**Comment by RBNXI** [comment]
Now it works for youtube, .torrent files and any streaming, but not for magnets.
If I open a youtube link with mpv, then close mpv and then open with --force-window --idle and select in the history the previous youtube video, it starts playing without any problem. The same with torrent files. That was solved.

But now only magnet files won´t work, for example if you have webtorrent [script](https://github.com/noctuid/mpv-webtorrent-hook/blob/master/webtorrent-hook.lua) and you open this [magnet link](magnet:?xt=urn:btih:N7RNND2O2P323NNVL6KLPW2O4PICF3VO&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&dn=%5BErai-raws%5D%20Black%20Clover%20%28TV%29%20-%20131%20%5B1080p%5D%5BMultiple%20Subtitle%5D.mkv), it starts playing without problem. But when you exit and then open mpv with --force-window --idle and select that magnet link in the history, it won´t play.

**Comment by hacel** [comment]
Let me know if it works now

**Comment by RBNXI** [comment]
Yes, now it works with every link I can try, including magnets, thank you.
