### ISSUE TITLE
Streams such as `rtmp://` won't load from recents

### ISSUE THREAD

**Issue by oakkitten** [hacel/mpv-scripts#6]
the script treats them as local files and prepends current directory to the url

**Comment by hacel** [comment]
Should be working correctly now.

**Comment by oakkitten** [comment]
the change seems to only cover `rtmp://` verbatim but mpv supports many more protocols, see `mpv --list-protocols`

**Comment by hacel** [comment]
Oh I didn't know about that command. Should I just make it check for "://" in the name? Not sure if that would cause any problems since I don't really use any of these protocols.
